name: functional_example

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  functional: 
    git:
      url: git://github.com/dhaval15/functional.git
      ref: master

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
