name: functional
description: A dart package which helps to use varius functional paradigms like function currying, piping.
version: 1.0.0-nullsafety.0
homepage: https://github.com/dhaval15/functional

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
